/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef _COMM_SHOP_H_
#define _COMM_SHOP_H_

#include "aminer.h"
#include <comm/comm.h>
#include "../defs.h"
#include "../msg.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum tCommShopPage {
	COMM_SHOP_PAGE_WAREHOUSE,
	COMM_SHOP_PAGE_WORKSHOP,
	// Office - must be same order as MSG_PAGE_* in defs.h
	COMM_SHOP_PAGE_OFFICE_MAIN,
	COMM_SHOP_PAGE_OFFICE_LIST_MIETEK,
	COMM_SHOP_PAGE_OFFICE_LIST_KRYSTYNA,
	COMM_SHOP_PAGE_OFFICE_LIST_KOMISARZ,
	COMM_SHOP_PAGE_OFFICE_LIST_URZEDAS,
	COMM_SHOP_PAGE_OFFICE_LIST_ARCH,
	COMM_SHOP_PAGE_OFFICE_LIST_PRISONER,
	COMM_SHOP_PAGE_OFFICE_LIST_AGENT,
	COMM_SHOP_PAGE_OFFICE_LIST_SCI,
	COMM_SHOP_PAGE_OFFICE_LIST_CRYO,
	COMM_SHOP_PAGE_OFFICE_LIST_JAY,

	COMM_SHOP_PAGE_OFFICE_MIETEK_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_MIETEK_WELCOME,
	COMM_SHOP_PAGE_OFFICE_MIETEK_FIRST_PLAN,
	COMM_SHOP_PAGE_OFFICE_MIETEK_PLAN_COMPLETE,
	COMM_SHOP_PAGE_OFFICE_MIETEK_PROTEST_START,
	COMM_SHOP_PAGE_OFFICE_MIETEK_PROTEST_STRIKE,
	COMM_SHOP_PAGE_OFFICE_MIETEK_CAPSULE_FOUND,

	COMM_SHOP_PAGE_OFFICE_KRYSTYNA_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_KRYSTYNA_ACCOUNTING,
	COMM_SHOP_PAGE_OFFICE_KRYSTYNA_PROTEST_WARNING,

	COMM_SHOP_PAGE_OFFICE_URZEDAS_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_URZEDAS_WELCOME,
	COMM_SHOP_PAGE_OFFICE_URZEDAS_FIRST_PLAN,
	COMM_SHOP_PAGE_OFFICE_URZEDAS_PLAN_COMPLETE,
	COMM_SHOP_PAGE_OFFICE_URZEDAS_PLAN_DELAYED,
	COMM_SHOP_PAGE_OFFICE_URZEDAS_PLAN_ACCOLADE,
	COMM_SHOP_PAGE_OFFICE_URZEDAS_BRIBE,

	COMM_SHOP_PAGE_OFFICE_KOMISARZ_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_WELCOME,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_DINO_INTRO,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_REBUKE_1,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_REBUKE_2,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_REBUKE_3,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_ARCH_ACCOLADE,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_QUESTIONING,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_REPORTING_LIST,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_REPORTING_GATE,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_REPORTING_TELEPORT_PARTS,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_REPORTING_AGENT,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_QUESTIONING_ACCOLADE,
	COMM_SHOP_PAGE_OFFICE_KOMISARZ_GATE_OPENING,

	COMM_SHOP_PAGE_OFFICE_ARCH_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_ARCH_WELCOME,
	COMM_SHOP_PAGE_OFFICE_ARCH_PLAN_FAIL,
	COMM_SHOP_PAGE_OFFICE_ARCH_ACCOLADE,
	COMM_SHOP_PAGE_OFFICE_ARCH_GATE_OPENED_DINO_INCOMPLETE,
	COMM_SHOP_PAGE_OFFICE_ARCH_GATE_OPENED_DINO_COMPLETE,
	COMM_SHOP_PAGE_OFFICE_ARCH_GATE_DESTROYED,

	COMM_SHOP_PAGE_OFFICE_PRISONER_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_PRISONER_WELCOME,
	COMM_SHOP_PAGE_OFFICE_PRISONER_GATE_DESTROYED,
	COMM_SHOP_PAGE_OFFICE_PRISONER_RADIO_1,
	COMM_SHOP_PAGE_OFFICE_PRISONER_RADIO_2,
	COMM_SHOP_PAGE_OFFICE_PRISONER_RADIO_3,

	COMM_SHOP_PAGE_OFFICE_AGENT_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_AGENT_WELCOME,
	COMM_SHOP_PAGE_OFFICE_AGENT_SCIENTISTS,
	COMM_SHOP_PAGE_OFFICE_AGENT_SELL_CRATES,
	COMM_SHOP_PAGE_OFFICE_AGENT_ESCAPE,
	COMM_SHOP_PAGE_OFFICE_AGENT_EPILOGUE,

	COMM_SHOP_PAGE_OFFICE_SCIENTIST_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_SCIENTIST_WELCOME,
	COMM_SHOP_PAGE_OFFICE_SCIENTIST_FIRST_CRATE,
	COMM_SHOP_PAGE_OFFICE_SCIENTIST_CRATE_TELEPORTER,
	COMM_SHOP_PAGE_OFFICE_SCIENTIST_ESCAPE,
	COMM_SHOP_PAGE_OFFICE_SCIENTIST_EPILOGUE,

	COMM_SHOP_PAGE_OFFICE_CRYO_DOSSIER,
	COMM_SHOP_PAGE_OFFICE_CRYO_TRAMIEL,
	COMM_SHOP_PAGE_OFFICE_CRYO_CONSOLE,
	COMM_SHOP_PAGE_CRYO_SUCCESS,

	COMM_SHOP_PAGE_JAY_DOSSIER,
	COMM_SHOP_PAGE_JAY_CONGRATS,

	// Intro & Outro
	COMM_SHOP_PAGE_NEWS_ACCOLADES,
	COMM_SHOP_PAGE_NEWS_GATE_ENEMY,
	COMM_SHOP_PAGE_NEWS_GATE_RED,
	COMM_SHOP_PAGE_NEWS_ESCAPE_FAIL,
	COMM_SHOP_PAGE_NEWS_RIOTS,
	// Subpages
	COMM_SHOP_PAGE_SOKOBAN,
	COMM_SHOP_PAGE_MARKET,
	// Gate cutscene
	COMM_SHOP_PAGE_ARCH_GATE_PLEA,
	COMM_SHOP_PAGE_PRISONER_GATE_PLEA,
	COMM_SHOP_PAGE_GATE_DILEMMA,

	COMM_SHOP_PAGE_COUNT
} tCommShopPage;

typedef enum tTabNavigationState {
	TAB_NAVIGATION_STATE_DISABLED,
	TAB_NAVIGATION_STATE_ENABLED,
	TAB_NAVIGATION_STATE_DISABLING,
} tTabNavigationState;

extern tState g_sStateShop;

UBYTE commShopIsActive(void);

tCommShopPage commShopGetCurrentPage(void);

tCommTab commShopPageToTab(tCommShopPage ePage);

tMsg commShopPageToTitle(tCommShopPage ePage);

void commShopChangePage(tCommShopPage eCameFrom, tCommShopPage ePage);

void commShopGoBack(void);

tTabNavigationState commShopGetTabNavigationState(void);

void commShopFocusOnTabNavigation(void);

#ifdef __cplusplus
}
#endif

#endif // _COMM_SHOP_H_
